In [1]:
#Importing Python Modules Pandas, Numpy, Seaborn and MetaplotLib
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#Loading HCV dataset into variable df by using pandas
df = pd.read_csv("F:\Data Science Course\Joyita\HCV - CMV\hcvdata.csv")

In [3]:
#To view first 5 rows of the dataset
df.head()

Unnamed: 0       Category  Age Sex   ALB   ALP   ALT   AST   BIL    CHE  \
0           1  0=Blood Donor   32   m  38.5  52.5   7.7  22.1   7.5   6.93   
1           2  0=Blood Donor   32   m  38.5  70.3  18.0  24.7   3.9  11.17   
2           3  0=Blood Donor   32   m  46.9  74.7  36.2  52.6   6.1   8.84   
3           4  0=Blood Donor   32   m  43.2  52.0  30.6  22.6  18.9   7.33   
4           5  0=Blood Donor   32   m  39.2  74.1  32.6  24.8   9.6   9.15   

   CHOL   CREA   GGT  PROT  
0  3.23  106.0  12.1  69.0  
1  4.80   74.0  15.6  76.5  
2  5.20   86.0  33.2  79.3  
3  4.74   80.0  33.8  75.7  
4  4.32   76.0  29.9  68.7

In [4]:
df.shape

(615, 14)

In [5]:
df.isnull().sum()

Unnamed: 0     0
Category       0
Age            0
Sex            0
ALB            1
ALP           18
ALT            1
AST            0
BIL            0
CHE            0
CHOL          10
CREA           0
GGT            0
PROT           1
dtype: int64

In [6]:
df.isnull().sum() / len(df)

Unnamed: 0    0.000000
Category      0.000000
Age           0.000000
Sex           0.000000
ALB           0.001626
ALP           0.029268
ALT           0.001626
AST           0.000000
BIL           0.000000
CHE           0.000000
CHOL          0.016260
CREA          0.000000
GGT           0.000000
PROT          0.001626
dtype: float64

In [7]:
#df.dropna(how="any").shape

In [8]:
df = df.fillna(method = 'ffill')

In [9]:
df.isnull().sum()

Unnamed: 0    0
Category      0
Age           0
Sex           0
ALB           0
ALP           0
ALT           0
AST           0
BIL           0
CHE           0
CHOL          0
CREA          0
GGT           0
PROT          0
dtype: int64

In [10]:
def Category(x):
    if(x == "0=Blood Donor"):
        return "0"
    elif(x == "0s=suspect Blood Donor"):
        return "1"
    elif(x == "1=Hepatitis"):
        return "2"
    elif(x == "2=Fibrosis"):
        return "3"
    elif(x == "3=Cirrhosis"):
        return "4"

In [11]:
df["Category"] = df["Category"].apply(lambda x : Category(x))
df

Unnamed: 0 Category  Age Sex   ALB    ALP    ALT    AST   BIL    CHE  \
0             1        0   32   m  38.5   52.5    7.7   22.1   7.5   6.93   
1             2        0   32   m  38.5   70.3   18.0   24.7   3.9  11.17   
2             3        0   32   m  46.9   74.7   36.2   52.6   6.1   8.84   
3             4        0   32   m  43.2   52.0   30.6   22.6  18.9   7.33   
4             5        0   32   m  39.2   74.1   32.6   24.8   9.6   9.15   
..          ...      ...  ...  ..   ...    ...    ...    ...   ...    ...   
610         611        4   62   f  32.0  416.6    5.9  110.3  50.0   5.57   
611         612        4   64   f  24.0  102.8    2.9   44.4  20.0   1.54   
612         613        4   64   f  29.0   87.3    3.5   99.0  48.0   1.66   
613         614        4   46   f  33.0   87.3   39.0   62.0  20.0   3.56   
614         615        4   59   f  36.0   87.3  100.0   80.0  12.0   9.07   

     CHOL   CREA    GGT  PROT  
0    3.23  106.0   12.1  69.0  
1    4.80   74.0   15.6  76.5  
2    5.20   86.0   33.2  79.3  
3    4.74   80.0   33.8  75.7  
4    4.32   76.0   29.9  68.7  
..    ...    ...    ...   ...  
610  6.30   55.7  650.9  68.5  
611  3.02   63.0   35.9  71.3  
612  3.63   66.7   64.2  82.0  
613  4.20   52.0   50.0  71.0  
614  5.30   67.0   34.0  68.0  

[615 rows x 14 columns]

In [12]:
def Sex(y):
    if(y == "f"):
        return "0"
    elif(y == "m"):
        return "1"

In [13]:
df["Sex"] = df["Sex"].apply(lambda y : Sex(y))
df

Unnamed: 0 Category  Age Sex   ALB    ALP    ALT    AST   BIL    CHE  \
0             1        0   32   1  38.5   52.5    7.7   22.1   7.5   6.93   
1             2        0   32   1  38.5   70.3   18.0   24.7   3.9  11.17   
2             3        0   32   1  46.9   74.7   36.2   52.6   6.1   8.84   
3             4        0   32   1  43.2   52.0   30.6   22.6  18.9   7.33   
4             5        0   32   1  39.2   74.1   32.6   24.8   9.6   9.15   
..          ...      ...  ...  ..   ...    ...    ...    ...   ...    ...   
610         611        4   62   0  32.0  416.6    5.9  110.3  50.0   5.57   
611         612        4   64   0  24.0  102.8    2.9   44.4  20.0   1.54   
612         613        4   64   0  29.0   87.3    3.5   99.0  48.0   1.66   
613         614        4   46   0  33.0   87.3   39.0   62.0  20.0   3.56   
614         615        4   59   0  36.0   87.3  100.0   80.0  12.0   9.07   

     CHOL   CREA    GGT  PROT  
0    3.23  106.0   12.1  69.0  
1    4.80   74.0   15.6  76.5  
2    5.20   86.0   33.2  79.3  
3    4.74   80.0   33.8  75.7  
4    4.32   76.0   29.9  68.7  
..    ...    ...    ...   ...  
610  6.30   55.7  650.9  68.5  
611  3.02   63.0   35.9  71.3  
612  3.63   66.7   64.2  82.0  
613  4.20   52.0   50.0  71.0  
614  5.30   67.0   34.0  68.0  

[615 rows x 14 columns]

In [14]:
#To add the new columns to the parent Data Set in the CSV File
df.to_csv("F:/Data Science Course/Joyita/HCV - CMV/test_hcvdata.csv")

In [15]:
df = pd.read_csv("F:/Data Science Course/Joyita/HCV - CMV/test_hcvdata.csv")
df.head()

Unnamed: 0  Unnamed: 0.1  Category  Age  Sex   ALB   ALP   ALT   AST   BIL  \
0           0             1         0   32    1  38.5  52.5   7.7  22.1   7.5   
1           1             2         0   32    1  38.5  70.3  18.0  24.7   3.9   
2           2             3         0   32    1  46.9  74.7  36.2  52.6   6.1   
3           3             4         0   32    1  43.2  52.0  30.6  22.6  18.9   
4           4             5         0   32    1  39.2  74.1  32.6  24.8   9.6   

     CHE  CHOL   CREA   GGT  PROT  
0   6.93  3.23  106.0  12.1  69.0  
1  11.17  4.80   74.0  15.6  76.5  
2   8.84  5.20   86.0  33.2  79.3  
3   7.33  4.74   80.0  33.8  75.7  
4   9.15  4.32   76.0  29.9  68.7

In [16]:
df.drop(["Unnamed: 0", "Unnamed: 0.1"], axis=1, inplace=True)
df.head()

Category  Age  Sex   ALB   ALP   ALT   AST   BIL    CHE  CHOL   CREA   GGT  \
0         0   32    1  38.5  52.5   7.7  22.1   7.5   6.93  3.23  106.0  12.1   
1         0   32    1  38.5  70.3  18.0  24.7   3.9  11.17  4.80   74.0  15.6   
2         0   32    1  46.9  74.7  36.2  52.6   6.1   8.84  5.20   86.0  33.2   
3         0   32    1  43.2  52.0  30.6  22.6  18.9   7.33  4.74   80.0  33.8   
4         0   32    1  39.2  74.1  32.6  24.8   9.6   9.15  4.32   76.0  29.9   

   PROT  
0  69.0  
1  76.5  
2  79.3  
3  75.7  
4  68.7

In [17]:
df["Category"].value_counts()

0    533
4     30
2     24
3     21
1      7
Name: Category, dtype: int64

Calculating VIF 
Ideally VIF should be less than or equal to 5

In [18]:
# Import Library for VIF
from statsmodels.stats.outliers_influence import variance_inflation_factor

def calc_vif(X):

    #Calculating VIF
    vif=pd.DataFrame()
    vif["variables"] = X.columns
    vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
    
    return(vif)

In [19]:
X = df.iloc[:,:-1]
calc_vif(X)

variables        VIF
0   Category   2.876546
1        Age  19.889332
2        Sex   3.052662
3        ALB  34.492194
4        ALP  10.121731
5        ALT   2.390958
6        AST   4.224136
7        BIL   1.840639
8        CHE  22.873785
9       CHOL  31.294360
10      CREA   4.206319
11       GGT   2.780284

In [20]:
#spliting independent features and target label
X = df.iloc[:,1:]  #independent features
Y = df["Category"]  #dependent feature or target 

In [21]:
X.head()

Age  Sex   ALB   ALP   ALT   AST   BIL    CHE  CHOL   CREA   GGT  PROT
0   32    1  38.5  52.5   7.7  22.1   7.5   6.93  3.23  106.0  12.1  69.0
1   32    1  38.5  70.3  18.0  24.7   3.9  11.17  4.80   74.0  15.6  76.5
2   32    1  46.9  74.7  36.2  52.6   6.1   8.84  5.20   86.0  33.2  79.3
3   32    1  43.2  52.0  30.6  22.6  18.9   7.33  4.74   80.0  33.8  75.7
4   32    1  39.2  74.1  32.6  24.8   9.6   9.15  4.32   76.0  29.9  68.7

In [22]:
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: Category, dtype: int64

In [23]:
#SKLearn for train and test split

from sklearn.model_selection import train_test_split
from sklearn.metrics import *

#train ==> i will teach my model, frame mathematical equation
#test

In [24]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, train_size = 0.8, random_state = 0)

In [25]:
X_train

Age  Sex   ALB   ALP   ALT    AST   BIL    CHE  CHOL   CREA    GGT  PROT
298   65    1  43.1  64.8  43.1   35.6   9.5   9.60  4.03   78.0   21.9  71.5
470   52    0  36.7  87.6  34.3   30.8  17.7  10.12  6.98   72.0   24.2  66.3
157   46    1  49.7  48.2  11.5   17.6  11.2   6.74  3.71  106.0   10.6  75.2
577   36    0  46.0  39.3  67.1  161.9  13.0   9.24  4.81   65.3   60.0  73.9
285   61    1  38.9  59.5  22.8   30.9   6.3   9.45  5.23   95.0   20.3  71.4
..   ...  ...   ...   ...   ...    ...   ...    ...   ...    ...    ...   ...
277   60    1  40.4  46.8  17.7   25.7  13.5   5.79  5.42   92.0   19.2  70.0
9     32    1  42.4  86.3  20.3   20.0  35.2   5.46  4.45   81.0   15.9  69.9
359   38    0  40.0  73.5  16.6   19.2   8.3   5.23  5.52   54.0   24.0  71.0
192   49    1  44.3  84.1  29.0   29.0  16.2   8.18  4.65   87.0   21.9  70.8
559   58    1  43.0  99.1  12.2   63.2  13.0   5.95  6.15  147.3  491.0  65.6

[492 rows x 12 columns]

In [26]:
Y_train

298    0
470    0
157    0
577    3
285    0
      ..
277    0
9      0
359    0
192    0
559    2
Name: Category, Length: 492, dtype: int64

In [27]:
from sklearn.preprocessing import MinMaxScaler

min_scalar = MinMaxScaler()
min_scalar.fit_transform(X_train) 
min_scalar.transform(X_test) 

array([[0.29310345, 1.        , 0.48885587, ..., 0.18413894, 0.02631579,
        0.69469027],
       [0.63793103, 0.        , 0.448737  , ..., 0.11717933, 0.21733746,
        0.48451327],
       [0.55172414, 1.        , 0.46062407, ..., 0.16112157, 0.04845201,
        0.62389381],
       ...,
       [0.63793103, 0.        , 0.27191679, ..., 0.09834693, 0.02198142,
        0.40486726],
       [0.55172414, 1.        , 0.41753343, ..., 0.14270768, 0.11068111,
        0.70575221],
       [0.67241379, 1.        , 0.38632987, ..., 0.17786148, 0.02105263,
        0.57743363]])

In [28]:
#Model Development and Prediction

#sklearn model to load Logistic regression package
from sklearn.linear_model import LogisticRegression
#max_iter=1200000, dual=False , class_weight="balanced", penalty="none"
logreg = LogisticRegression(solver = "sag", max_iter=10000)

#fit training data
logreg.fit(X_train, Y_train)

#predict unseen data on trained model
Y_pred = logreg.predict(X_test)

In [29]:
Y_pred

array([0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0,
       0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 4,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       4, 0, 1, 0, 0, 0, 3, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 4, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0], dtype=int64)

In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
conf_matrix = confusion_matrix(Y_test, Y_pred)

In [32]:
conf_matrix

array([[108,   0,   0,   0,   0],
       [  1,   1,   0,   0,   0],
       [  0,   0,   1,   2,   1],
       [  0,   0,   0,   2,   0],
       [  0,   0,   0,   0,   7]], dtype=int64)

In [33]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, Y_pred)
accuracy

0.967479674796748

In [34]:
from sklearn.metrics import precision_score
precision = precision_score(Y_test, Y_pred, average='weighted')
precision

0.976700604162005

In [35]:
from sklearn.metrics import recall_score
recall = recall_score(Y_test, Y_pred, average='weighted')
recall

0.967479674796748

In [36]:
from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

Y_pred_proba = logreg.predict_proba(X_test)[::,1]
fpr, tpr, _ = roc_curve(Y_test,  Y_pred, pos_label=None)
auc = roc_auc_score(Y_test, Y_pred, average='weighted')
plt.plot(fpr,tpr,label="data 1, auc="+str(auc))
plt.xlabel("False Positives")
plt.ylabel("True Positives")
plt.legend(loc=4)
plt.show()

ValueError: multiclass format is not supported